
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package fr.n7.stl.block;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int UL_Second = 37;
  public static final int UL_Sinon = 49;
  public static final int UL_Egal = 20;
  public static final int UL_Point = 16;
  public static final int UL_Double_Plus_Prefixe = 23;
  public static final int UL_Double_Egal = 46;
  public static final int UL_Point_Exclamation = 19;
  public static final int UL_Chaine = 65;
  public static final int UL_Retour = 53;
  public static final int UL_Type_Flottant = 62;
  public static final int UL_Asterisque = 28;
  public static final int UL_Vrai = 70;
  public static final int UL_Inferieur = 42;
  public static final int UL_Protege = 6;
  public static final int UL_Classe = 2;
  public static final int UL_Double_Moins_Prefixe = 24;
  public static final int UL_Parenthese_Fermante = 35;
  public static final int UL_Caractere = 66;
  public static final int UL_Crochet_Fermant = 41;
  public static final int UL_Parenthese_Ouvrante = 34;
  public static final int UL_Type_Caractere = 59;
  public static final int UL_Point_Virgule = 14;
  public static final int UL_Type_Booleen = 58;
  public static final int UL_Definition_Constante = 54;
  public static final int UL_Accolade_Fermante = 39;
  public static final int UL_Accolade_Ouvrante = 38;
  public static final int UL_Point_Interrogation = 18;
  public static final int UL_Inferieur_Egal = 44;
  public static final int UL_Superieur = 43;
  public static final int UL_Nombre_Flottant = 68;
  public static final int UL_Nul = 69;
  public static final int UL_Exclamation_Egal = 47;
  public static final int UL_Virgule = 15;
  public static final int UL_Public = 4;
  public static final int UL_Moi = 12;
  public static final int UL_Oblique = 29;
  public static final int UL_Crochet_Ouvrant = 40;
  public static final int UL_De_Classe = 9;
  public static final int UL_Methode_Principale = 11;
  public static final int UL_Abstrait = 8;
  public static final int UL_Definitif = 7;
  public static final int UL_Double_Esperluette = 33;
  public static final int UL_Identificateur = 64;
  public static final int UL_Type_Vide = 63;
  public static final int UL_Moins = 26;
  public static final int UL_Classe_Principale = 10;
  public static final int UL_Enregistrement = 56;
  public static final int EOF = 0;
  public static final int UL_Deux_Points = 17;
  public static final int UL_Type_Chaine = 60;
  public static final int error = 1;
  public static final int UL_Nouveau = 51;
  public static final int UL_Type_Entier = 61;
  public static final int UL_Double_Barre = 32;
  public static final int UL_Afficher = 52;
  public static final int UL_Plus = 25;
  public static final int UL_Super = 13;
  public static final int UL_Esperluette = 31;
  public static final int UL_Herite = 3;
  public static final int UL_Enumeration = 57;
  public static final int UL_Prive = 5;
  public static final int UL_Superieur_Egal = 45;
  public static final int UL_Double_Plus = 21;
  public static final int UL_Tant_Que = 50;
  public static final int UL_Faux = 71;
  public static final int UL_Definition_Type = 55;
  public static final int UL_Si = 48;
  public static final int UL_Nombre_Entier = 67;
  public static final int UL_Pour_Cent = 30;
  public static final int UL_Double_Moins = 22;
  public static final int UL_Premier = 36;
  public static final int UL_Moins_Unaire = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UL_Classe",
  "UL_Herite",
  "UL_Public",
  "UL_Prive",
  "UL_Protege",
  "UL_Definitif",
  "UL_Abstrait",
  "UL_De_Classe",
  "UL_Classe_Principale",
  "UL_Methode_Principale",
  "UL_Moi",
  "UL_Super",
  "UL_Point_Virgule",
  "UL_Virgule",
  "UL_Point",
  "UL_Deux_Points",
  "UL_Point_Interrogation",
  "UL_Point_Exclamation",
  "UL_Egal",
  "UL_Double_Plus",
  "UL_Double_Moins",
  "UL_Double_Plus_Prefixe",
  "UL_Double_Moins_Prefixe",
  "UL_Plus",
  "UL_Moins",
  "UL_Moins_Unaire",
  "UL_Asterisque",
  "UL_Oblique",
  "UL_Pour_Cent",
  "UL_Esperluette",
  "UL_Double_Barre",
  "UL_Double_Esperluette",
  "UL_Parenthese_Ouvrante",
  "UL_Parenthese_Fermante",
  "UL_Premier",
  "UL_Second",
  "UL_Accolade_Ouvrante",
  "UL_Accolade_Fermante",
  "UL_Crochet_Ouvrant",
  "UL_Crochet_Fermant",
  "UL_Inferieur",
  "UL_Superieur",
  "UL_Inferieur_Egal",
  "UL_Superieur_Egal",
  "UL_Double_Egal",
  "UL_Exclamation_Egal",
  "UL_Si",
  "UL_Sinon",
  "UL_Tant_Que",
  "UL_Nouveau",
  "UL_Afficher",
  "UL_Retour",
  "UL_Definition_Constante",
  "UL_Definition_Type",
  "UL_Enregistrement",
  "UL_Enumeration",
  "UL_Type_Booleen",
  "UL_Type_Caractere",
  "UL_Type_Chaine",
  "UL_Type_Entier",
  "UL_Type_Flottant",
  "UL_Type_Vide",
  "UL_Identificateur",
  "UL_Chaine",
  "UL_Caractere",
  "UL_Nombre_Entier",
  "UL_Nombre_Flottant",
  "UL_Nul",
  "UL_Vrai",
  "UL_Faux"
  };
}

